from dataclasses import dataclass, field
from typing import Any


@dataclass
class AnalysisRequest:
    """
    Contract received by the geospatial module.

    Polygon must be provided in EPSG:4326.
    Dataset specs are already resolved by the backend.
    """

    analysis_id: str
    polygon: dict[str, Any]
    dataset_specs: list[dict[str, Any]]
    indicators: list[str]
    processing_config: dict[str, Any] = field(default_factory=dict)


@dataclass
class ArtifactDescriptor:
    """
    Describes an output artifact generated by geospatial processing.

    Paths are relative to the analysis output directory.
    URLs are not stored in this contract.
    """

    artifact_id: str
    kind: str
    relative_path: str
    dataset_id: str | None = None


@dataclass
class GeospatialResult:
    """
    Scientific result returned by the geospatial module.
    """

    metrics: dict[str, Any]
    series: list[dict[str, Any]]
    comparisons: list[dict[str, Any]]
    quality: dict[str, Any]
    warnings: list[str]
    provenance: dict[str, Any]
    artifacts: list[ArtifactDescriptor] = field(default_factory=list)


@dataclass
class ReportPayload:
    """
    Data supplied to the report generator.

    Person 4 owns the scientific methods and wording.
    Person 2 owns report delivery/storage.
    """

    analysis_id: str
    inputs: dict[str, Any]
    prediction: dict[str, Any] | None
    geospatial_result: GeospatialResult
    dataset_sources: list[dict[str, Any]]
    artifact_paths: list[str] = field(default_factory=list)