"""create initial watershed schema

Revision ID: e4848f47f4f6
Revises: 
Create Date: 2026-10-02 16:32:54.963887
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry


# revision identifiers, used by Alembic.
revision: str = 'e4848f47f4f6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    op.create_table('datasets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=512), nullable=False),
    sa.Column('acquisition_date', sa.Date(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('crs', sa.String(length=128), nullable=False),
    sa.Column('transform', sa.JSON(), nullable=False),
    sa.Column('resolution', sa.JSON(), nullable=False),
    sa.Column('bounds', sa.JSON(), nullable=False),
    sa.Column('bands', sa.JSON(), nullable=False),
    sa.Column('scale', sa.JSON(), nullable=True),
    sa.Column('offset', sa.JSON(), nullable=True),
    sa.Column('quality_metadata', sa.JSON(), nullable=True),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('manifest', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_datasets_sha256'), 'datasets', ['sha256'], unique=True)
    op.create_table('photos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('safe_path', sa.String(length=1024), nullable=False),
    sa.Column('original_name', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('gps_latitude', sa.Double(), nullable=True),
    sa.Column('gps_longitude', sa.Double(), nullable=True),
    sa.Column('captured_at', sa.Date(), nullable=True),
    sa.Column('exif_status', sa.String(length=32), nullable=False),
    sa.Column('location', Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photos_sha256'), 'photos', ['sha256'], unique=True)
    op.create_table('predictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('photo_id', sa.UUID(), nullable=False),
    sa.Column('model_version', sa.String(length=128), nullable=False),
    sa.Column('model_hash', sa.String(length=128), nullable=False),
    sa.Column('label_id', sa.Integer(), nullable=False),
    sa.Column('predicted_label', sa.String(length=256), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('top_candidate', sa.String(length=256), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('review_flag', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_photo_id'), 'predictions', ['photo_id'], unique=False)
    op.create_table('analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('photo_id', sa.UUID(), nullable=False),
    sa.Column('prediction_id', sa.UUID(), nullable=False),
    sa.Column('prediction_snapshot', sa.JSON(), nullable=False),
    sa.Column(
        'polygon',
        Geometry(
            geometry_type='POLYGON',
            srid=4326,
            dimension=2,
            from_text='ST_GeomFromEWKT',
            name='geometry',
        ),
        nullable=False,
    ),
    sa.Column('indicators', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('client_request_key', sa.String(length=256), nullable=True),
    sa.Column('worker_lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('worker_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_request_key')
    )
    op.create_index(op.f('ix_analyses_photo_id'), 'analyses', ['photo_id'], unique=False)
    op.create_index(op.f('ix_analyses_prediction_id'), 'analyses', ['prediction_id'], unique=False)
    op.create_index(op.f('ix_analyses_status'), 'analyses', ['status'], unique=False)
    op.create_table('analysis_datasets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('dataset_metadata_snapshot', sa.JSON(), nullable=False),
    sa.Column('dataset_sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_id', 'dataset_id', name='uq_analysis_datasets_analysis_dataset')
    )
    op.create_index(op.f('ix_analysis_datasets_analysis_id'), 'analysis_datasets', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_analysis_datasets_dataset_id'), 'analysis_datasets', ['dataset_id'], unique=False)
    op.create_table('analysis_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('schema_version', sa.String(length=64), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('pipeline_version', sa.String(length=128), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_results_analysis_id'), 'analysis_results', ['analysis_id'], unique=True)
    op.create_table('analysis_warnings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=128), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('scope', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_warnings_analysis_id'), 'analysis_warnings', ['analysis_id'], unique=False)
    op.create_table('artifacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=128), nullable=False),
    sa.Column('safe_relative_path', sa.String(length=1024), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artifacts_analysis_id'), 'artifacts', ['analysis_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_artifacts_analysis_id'), table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index(op.f('ix_analysis_warnings_analysis_id'), table_name='analysis_warnings')
    op.drop_table('analysis_warnings')
    op.drop_index(op.f('ix_analysis_results_analysis_id'), table_name='analysis_results')
    op.drop_table('analysis_results')
    op.drop_index(op.f('ix_analysis_datasets_dataset_id'), table_name='analysis_datasets')
    op.drop_index(op.f('ix_analysis_datasets_analysis_id'), table_name='analysis_datasets')
    op.drop_table('analysis_datasets')
    op.drop_index(op.f('ix_analyses_status'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_prediction_id'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_photo_id'), table_name='analyses')
    op.drop_table('analyses')
    op.drop_index(op.f('ix_predictions_photo_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_photos_sha256'), table_name='photos')
    op.drop_table('photos')
    op.drop_index(op.f('ix_datasets_sha256'), table_name='datasets')
    op.drop_table('datasets')
    # ### end Alembic commands ###